### ISSUE TITLE
Run Snyk only when changes are made to a `package.json`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex-js#92]
if we move the `Snyk` to its own action, we can use the following `on` trigger to only run the Snyk check when changes are made to `package.json`s. I think this makes sense because licenses won't change without version bumps (presumably?)

```yaml
on:
  push:
    paths:
      - 'packages/protocol/package.json'
      - 'packages/http-client/package.json'
      - 'packages/http-server/package.json'
```
